version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: amitvashist7/get-started:part2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
    #links:
    #  - redis
  redis:
    image: redis
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"         
    networks:
      - webnet 
  viz:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "8080:8080"
networks:
  webnet:
